import test from'node:test';import assert from'node:assert/strict';import{createAcademySession,executeAcademyCommand,academyPrompt}from'../public/lib/network-academy-engine.js';
const run=(session,...commands)=>commands.map(command=>executeAcademyCommand(session,command));

test('Brocade workflow creates and activates alias-zone-config chain',()=>{const s=createAcademySession('brocade');const results=run(s,'alicreate host1, 10:00:00:00:00:00:00:01','alicreate array1, 50:00:00:00:00:00:00:01','zonecreate z_host1_array1, host1; array1','cfgcreate cfg_prod, z_host1_array1','cfgenable cfg_prod');assert.ok(results.every(x=>x.ok));assert.equal(s.state.effectiveConfig,'cfg_prod')});
test('Brocade refuses deletion while an object is referenced',()=>{const s=createAcademySession('brocade');run(s,'alicreate host1, 10:00:00:00:00:00:00:01','zonecreate z1, host1');const r=executeAcademyCommand(s,'alidelete host1');assert.equal(r.ok,false);assert.match(r.output,/referenced/)});
test('Brocade delete chain succeeds in dependency order',()=>{const s=createAcademySession('brocade');run(s,'alicreate host1, 10:00:00:00:00:00:00:01','zonecreate z1, host1','cfgcreate c1, z1','cfgdelete c1','zonedelete z1','alidelete host1');assert.deepEqual(s.state.aliases,{});assert.deepEqual(s.state.zones,{})});
test('undo restores destructive state change',()=>{const s=createAcademySession('brocade');run(s,'alicreate host1, 10:00:00:00:00:00:00:01','alidelete host1','undo');assert.ok(s.state.aliases.host1)});
test('Cisco mode prompts and VSAN state are contextual',()=>{const s=createAcademySession('cisco');run(s,'configure terminal','vsan 20');assert.equal(academyPrompt(s),'MDS-A(config)#');assert.ok(s.state.vsans[20])});
test('Cisco workflow creates alias zone zoneset and activates it',()=>{const s=createAcademySession('cisco');const results=run(s,'configure terminal','vsan 20','device-alias database','device-alias name host1 pwwn 10:00:00:00:00:00:00:01','device-alias commit','exit','zone name z1 vsan 20','member device-alias host1','exit','zoneset name zs1 vsan 20','member z1','exit','zoneset activate name zs1 vsan 20');assert.ok(results.every(x=>x.ok));assert.equal(s.state.activeZonesets[20],'zs1')});
test('Cisco no form cannot remove an active zoneset',()=>{const s=createAcademySession('cisco');run(s,'configure terminal','vsan 20','zone name z1 vsan 20','exit','zoneset name zs1 vsan 20','member z1','exit','zoneset activate name zs1 vsan 20');const r=executeAcademyCommand(s,'no zoneset name zs1 vsan 20');assert.equal(r.ok,false);assert.match(r.output,/active/)});
test('iSCSI workflow creates target, portal, LUN, discovery, and session',()=>{const s=createAcademySession('iscsi'),iqn='iqn.2026-08.lab:target1';const results=run(s,`target create ${iqn}`,`portal add ${iqn} 192.0.2.20:3260`,`lun map ${iqn} 0 /dev/simdisk0`,'discover',`login ${iqn}`);assert.ok(results.every(x=>x.ok));assert.equal(s.state.initiators.host1.sessions.length,1)});
test('iSCSI refuses target deletion with an active session',()=>{const s=createAcademySession('iscsi'),iqn='iqn.2026-08.lab:t1';run(s,`target create ${iqn}`,`portal add ${iqn} 192.0.2.20:3260`,'discover',`login ${iqn}`);const r=executeAcademyCommand(s,`target delete ${iqn}`);assert.equal(r.ok,false);assert.match(r.output,/logout/)});
test('iSCSI CHAP rejects wrong credentials and accepts correct credentials',()=>{const s=createAcademySession('iscsi'),iqn='iqn.2026-08.lab:t1';run(s,`target create ${iqn}`,`chap set ${iqn} learner strongsecret`,'discover');assert.equal(executeAcademyCommand(s,`login ${iqn} learner wrong`).ok,false);assert.equal(executeAcademyCommand(s,`login ${iqn} learner strongsecret`).ok,true)});
test('unsupported commands never mutate state',()=>{const s=createAcademySession('brocade'),before=JSON.stringify(s.state);const r=executeAcademyCommand(s,'format flash');assert.equal(r.ok,false);assert.equal(JSON.stringify(s.state),before)});
